### ISSUE TITLE
Compile fail (undefined reference to `pthread_create')

### ISSUE THREAD

**Issue by kobe0308** [TheLartians/Generator#1]
Hi
There is an error message When I build this project, The message as below: 

[ 16%] Linking CXX executable fibonacci
CMakeFiles/fibonacci.dir/examples/fibonacci.cpp.o: In function `std::thread::thread<lars::Generator<long>::begin() const::{lambda()#1}>(lars::Generator<long>::begin() const::{lambda()#1}&&)':
fibonacci.cpp:(.text._ZNSt6threadC2IZNK4lars9GeneratorIlE5beginEvEUlvE_JEEEOT_DpOT0_[_ZNSt6threadC5IZNK4lars9GeneratorIlE5beginEvEUlvE_JEEEOT_DpOT0_]+0x2f): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/fibonacci.dir/build.make:94: recipe for target 'fibonacci' failed
make[2]: *** [fibonacci] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/fibonacci.dir/all' failed
make[1]: *** [CMakeFiles/fibonacci.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

My solution:
Link pthread to target(example/test)

target_link_libraries( ${examplename} pthread)
target_link_libraries( ${testname} pthread)

**Comment by TheLartians** [comment]
Hey, thanks for letting me know! I've updated the CMakeLists and added some tests that also check the compilation process.
